import { MissionData } from "../world0";

export const world4Missions: MissionData[] = [
  {
    id: "auth-provider",
    title: "Clerk or Supabase Auth",
    slides: [
      {
        type: "text",
        title: "Intent",
        body: "Your app is a public park. Anyone can enter. We need to turn it into a private club. We need a Bouncer (Auth Provider).",
      },
      {
        type: "text",
        title: "How to talk to AI",
        body: "Tell AI you want to enable authentication using the tool you already have (Supabase).",
      },
      {
        type: "text",
        title: "Example message to AI",
        body: "I want to add email/password login to my Next.js app using Supabase Auth.\nCreate a login page with a form that signs the user in.\nUse the client component method.",
      },
      {
        type: "checklist",
        title: "Foundation: Provider Setup",
        prompt: "Enable the provider first.",
        items: [
          { id: "1", label: "Go to Supabase -> Authentication -> Providers" },
          { id: "2", label: "Enable Email/Password" },
          { id: "3", label: "Disable 'Confirm Email' (for faster testing)" }
        ],
      },
      {
        type: "miniChallenge",
        title: "Verification step",
        task: "Go to /login. Sign up with a fake email. Check Supabase -> Authentication -> Users. Is the user there?",
        example: "User created",
      }
    ],
  },
  {
    id: "route-protection",
    title: "Route Protection",
    slides: [
      {
        type: "text",
        title: "Intent",
        body: "A login page isn't enough. If someone knows the URL '/dashboard', they can just type it in. We need a guard dog (Middleware) to check every request.",
      },
      {
        type: "text",
        title: "How to talk to AI",
        body: "Ask for 'Middleware' that protects specific routes.",
      },
      {
        type: "text",
        title: "Example message to AI",
        body: "Create a middleware.ts file for Next.js.\nIf a user tries to visit /dashboard or /admin without being logged in, redirect them to /login.\nUse the Supabase auth helper.",
      },
      {
        type: "miniChallenge",
        title: "Verification step",
        task: "Open an Incognito window. Try to visit http://localhost:3000/dashboard. If you get bounced back to login, the guard dog is working.",
        example: "Redirected",
      }
    ],
  },
  {
    id: "user-profiles",
    title: "User Profiles",
    slides: [
      {
        type: "text",
        title: "Intent",
        body: "Auth only stores an email and ID. It doesn't store 'Avatar', 'Plan', or 'Bio'. We need a separate table for that data, linked to the user's ID.",
      },
      {
        type: "text",
        title: "How to talk to AI",
        body: "Ask for a table that links to 'auth.users'. This is a common pattern called 'Foreign Key'.",
      },
      {
        type: "text",
        title: "Example message to AI",
        body: "I need a profiles table that references the auth.users table.\nAdd columns for full_name and avatar_url.\nAlso, write a SQL trigger to automatically create a profile row when a new user signs up.",
      },
      {
        type: "checklist",
        title: "Verification step",
        prompt: "Test the trigger.",
        items: [
          { id: "1", label: "Run the SQL generated by AI" },
          { id: "2", label: "Sign up a NEW user" },
          { id: "3", label: "Check the 'profiles' table. Did a row appear automatically?" }
        ],
      },
      {
        type: "text",
        title: "Recovery Path",
        body: "If the trigger fails, ask AI: 'The trigger didn't work. Give me a SQL query to manually insert a profile for my existing user.'",
      }
    ],
  }
];
