import { MissionData } from "./missions/world0";

export type Mission = {
  id: string;
  title: string;
  description?: string;
  xpReward?: number;
};

export type World = {
  id: number;
  phaseId: number;
  slug: string;
  title: string;
  subtitle?: string;
  missions: Mission[];
  project?: string; // Description of the project
  blackBox?: {
    title: string;
    description: string;
  };
  secretDrop?: {
    title: string;
    description: string;
  };
  lockedByDefault?: boolean;
};

export type Phase = {
  id: number;
  title: string;
  subtitle?: string;
  worlds: World[];
};

export const curriculum: { phases: Phase[] } = {
  phases: [
    {
      id: 0,
      title: "Phase 0: Tutorial",
      worlds: [
        {
          id: 0,
          phaseId: 0,
          slug: "tutorial",
          title: "The Tutorial",
          subtitle: "Your First Vibe Check",
          missions: [
            { id: "what-is-vibe-coding", title: "What is Vibe Coding?", description: "Understand what you are actually learning here.", xpReward: 10 },
            { id: "overview-restaurant", title: "Overview: The Restaurant Analogy", description: "Learn the mental model of modern apps.", xpReward: 15 },
            { id: "frontend-fundamentals", title: "Frontend Fundamentals", description: "UI, Components, Rendering, and State.", xpReward: 10 },
            { id: "backend-fundamentals", title: "Backend Fundamentals", description: "Servers, Logic, Auth, and Endpoints.", xpReward: 10 },
            { id: "api-fundamentals", title: "API Fundamentals", description: "Requests, Responses, and the Contract.", xpReward: 10 },
            { id: "database-fundamentals", title: "Database Fundamentals", description: "Tables, Rows, Persistence, and Storage.", xpReward: 10 },
            { id: "devtools-fundamentals", title: "Dev Tools & Workflow", description: "Node, Git, IDEs, and Deployment.", xpReward: 10 },
            { id: "build-your-first-stack", title: "Build Your First Stack", description: "Apply everything by building a full Vibe Stack.", xpReward: 25 }
          ],
          blackBox: {
            title: "HTML, CSS, JS & The DOM",
            description: "What actually happens when you load a page."
          }
        }
      ]
    },
    {
      id: 1,
      title: "Phase 1: Ignition",
      subtitle: "Zero to One",
      worlds: [
        {
          id: 1,
          phaseId: 1,
          slug: "vibe-philosophy",
          title: "The Vibe Philosophy",
          subtitle: "Think like a founder",
          missions: [
            { id: "manifesto", title: "The Vibe Coder Manifesto", description: "Speed > Perfection", xpReward: 10 },
            { id: "tool-stack", title: "Your Tool Stack", description: "Cursor + V0 + Supabase + Claude", xpReward: 10 },
            { id: "context-game", title: "The Context Game", description: "Feeding docs without hallucination", xpReward: 10 },
            { id: "hello-world", title: "Hello World", description: "Deploy your first site in 15 minutes", xpReward: 10 }
          ],
          blackBox: {
            title: "How the browser renders your page",
            description: "The Critical Rendering Path."
          },
          secretDrop: {
            title: "AI Pair Programming Ritual",
            description: "Unlock the secrets of AI collaboration."
          }
        },
        {
          id: 2,
          phaseId: 1,
          slug: "god-mode-workflow",
          title: "God Mode Workflow",
          subtitle: "Coding becomes English class",
          missions: [
            { id: "composer-mastery", title: "Cursor Composer Mastery", xpReward: 10 },
            { id: "v0-to-code", title: "V0 to Code Pipeline", xpReward: 10 },
            { id: "iterative-prompting", title: "Iterative Prompting", xpReward: 10 },
            { id: "landing-page-project", title: "Build a Landing Page", description: "Use only natural language. No manual CSS.", xpReward: 10 }
          ],
          blackBox: {
            title: "React re-renders",
            description: "Component fundamentals and lifecycle."
          },
          secretDrop: {
            title: "Prompt Transfusion System",
            description: "Advanced prompting techniques."
          }
        }
      ]
    },
    {
      id: 2,
      title: "Phase 2: The Build",
      subtitle: "Build the Real SaaS",
      worlds: [
        {
          id: 3,
          phaseId: 2,
          slug: "the-brain-backend",
          title: "The Brain (Backend)",
          subtitle: "Don't learn SQL. Ask for data.",
          missions: [
            { id: "supabase-setup", title: "Supabase Setup", xpReward: 10 },
            { id: "schema-first", title: "Schema-First Design", description: "Generated by Claude", xpReward: 10 },
            { id: "env-vars", title: "Environment Variables", xpReward: 10 },
            { id: "frontend-connection", title: "Connect Frontend ↔ Backend", xpReward: 10 }
          ],
          project: "Your first real app: A Waitlist with database storage.",
          blackBox: {
            title: "SQL basics, Primary & Foreign Keys",
            description: "Database fundamentals."
          },
          secretDrop: {
            title: "Architecture Blueprint Method",
            description: "How to structure scalable apps."
          }
        },
        {
          id: 4,
          phaseId: 2,
          slug: "the-bouncer-auth",
          title: "The Bouncer (Auth)",
          subtitle: "Who gets in?",
          missions: [
            { id: "auth-provider", title: "Clerk or Supabase Auth", xpReward: 10 },
            { id: "route-protection", title: "Route Protection", xpReward: 10 },
            { id: "user-profiles", title: "User Profiles", xpReward: 10 }
          ],
          project: "Turn your Waitlist into a Private Dashboard.",
          blackBox: {
            title: "Sessions, cookies, JWTs",
            description: "Authentication mechanisms explained."
          }
        },
        {
          id: 5,
          phaseId: 2,
          slug: "the-magic-apis",
          title: "The Magic (APIs)",
          subtitle: "Your app gains superpowers",
          missions: [
            { id: "fetching-data", title: "Fetching External Data", xpReward: 10 },
            { id: "ai-connection", title: "Connecting OpenAI/Gemini", xpReward: 10 },
            { id: "streaming", title: "Streaming Text Animations", xpReward: 10 },
            { id: "webhooks", title: "Webhook Basics", xpReward: 10 }
          ],
          project: "Add an AI feature to your dashboard.",
          blackBox: {
            title: "HTTP Methods & Headers",
            description: "GET, POST, and request anatomy."
          }
        }
      ]
    },
    {
      id: 3,
      title: "Phase 3: The Grind",
      subtitle: "Where others quit. You won't.",
      worlds: [
        {
          id: 6,
          phaseId: 3,
          slug: "the-fixer-debugging",
          title: "The Fixer (Debugging)",
          subtitle: "The most important world.",
          missions: [
            { id: "recognizing-hallucinations", title: "Recognizing Hallucinations", xpReward: 10 },
            { id: "ai-fixes", title: "Using AI to Fix AI", xpReward: 10 },
            { id: "copy-paste-debug", title: "Copy-Paste Debugging", xpReward: 10 },
            { id: "git-save-game", title: "GitHub Desktop 'Save Game'", xpReward: 10 }
          ],
          project: "We break a repo → You fix it with AI.",
          blackBox: {
            title: "Console Errors & Network Tab",
            description: "Debugging tools in the browser."
          },
          secretDrop: {
            title: "No-Error Loop",
            description: "Systematic debugging workflow."
          }
        },
        {
          id: 7,
          phaseId: 3,
          slug: "the-polish-ui-ux",
          title: "The Polish (UI and UX)",
          subtitle: "Make it look expensive",
          missions: [
            { id: "shadcn-customization", title: "Shadcn Customization", xpReward: 10 },
            { id: "mobile-fixes", title: "Mobile Fixes", xpReward: 10 },
            { id: "responsiveness", title: "Responsiveness Prompts", xpReward: 10 },
            { id: "dark-mode", title: "Dark Mode Toggle", xpReward: 10 },
            { id: "toasts", title: "Toasts & Micro-interactions", xpReward: 10 }
          ],
          project: "UI Audit: Make your dashboard feel premium."
        }
      ]
    },
    {
      id: 4,
      title: "Phase 4: The Payday",
      subtitle: "The Business Layer",
      worlds: [
        {
          id: 8,
          phaseId: 4,
          slug: "the-cash-register",
          title: "The Cash Register",
          subtitle: "Let the app pay you",
          missions: [
            { id: "payment-provider", title: "Stripe vs LemonSqueezy", xpReward: 10 },
            { id: "checkout", title: "Setting up Checkout", xpReward: 10 },
            { id: "paywalls", title: "Gating Features", xpReward: 10 },
            { id: "webhooks-pro", title: "Webhooks for 'Pro' Status", xpReward: 10 }
          ],
          project: "Make yourself a real $1 payment.",
          blackBox: {
            title: "Webhook Security",
            description: "Signature verification and secure patterns."
          }
        },
        {
          id: 9,
          phaseId: 4,
          slug: "the-launch",
          title: "The Launch",
          subtitle: "Unlock your Founder Badge",
          lockedByDefault: true,
          missions: [
            { id: "domains", title: "Domain + DNS", xpReward: 10 },
            { id: "seo", title: "SEO Optimization via AI", xpReward: 10 },
            { id: "opengraph", title: "Open Graph Images", xpReward: 10 },
            { id: "posthog", title: "Posthog Analytics", xpReward: 10 }
          ],
          project: "Deploy your SaaS.",
          secretDrop: {
            title: "The Founder Protocol",
            description: "Golden Prompts Library download included."
          }
        },
        {
          id: 10,
          phaseId: 4,
          slug: "the-public-build-bonus",
          title: "The Public Build (Bonus)",
          subtitle: "The Growth Engine",
          missions: [
            { id: "recording-content", title: "Recording Coding Content", xpReward: 10 },
            { id: "build-in-public", title: "Build-in-Public Templates", xpReward: 10 },
            { id: "distribution", title: "Distribution Tactics", xpReward: 10 },
            { id: "community-flywheel", title: "Vibe Coder Community Flywheel", xpReward: 10 }
          ]
        }
      ]
    }
  ]
};
